# 🔢 NumPy Basics – Day 3
**Goal:** Learn fundamentals of NumPy arrays – creation, indexing, slicing, reshaping, and basic operations.  

# 1. Importing NumPy

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.2.5


# 2. Creating Arrays

In [2]:
# From Python list
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Multi-dimensional
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

# Using built-in functions
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
arange = np.arange(0, 10, 2)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Arange:", arange)

Array: [1 2 3 4 5]
Matrix:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]


# 3. Array Attributes

In [3]:
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Data type:", matrix.dtype)
print("Size (no. of elements):", matrix.size)

Shape: (2, 3)
Dimensions: 2
Data type: int64
Size (no. of elements): 6


# 4. Indexing & Slicing

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice (1:4):", arr[1:4])

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Second row:", matrix[1])
print("Element (0,2):", matrix[0, 2])

First element: 10
Last element: 50
Slice (1:4): [20 30 40]
Second row: [4 5 6]
Element (0,2): 3


# 5. Reshaping Arrays

In [5]:
arr = np.arange(1, 13)  # 1 to 12
print("Original:", arr)

reshaped = arr.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

flattened = reshaped.ravel()
print("Flattened:", flattened)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


# ✅ Summary (Day 3):

Learned array creation (zeros, ones, arange)
Explored attributes, indexing, slicing
Practiced reshaping and flattening arrays