# 🔢 NumPy Operations – Day 4
**Goal:** Learn numerical operations, statistics, and random number generation with NumPy.  

# 1. Element-wise Operations

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Square:", arr1 ** 2)

# 2. Aggregate Functions

In [4]:
data = np.array([5, 10, 15, 20, 25])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))

Sum: 75
Mean: 15.0
Median: 15.0
Standard Deviation: 7.0710678118654755
Variance: 50.0


# 3. Matrix Operations

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Dot product
print("Dot Product:\n", np.dot(A, B))

# Transpose
print("Transpose of A:\n", A.T)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Dot Product:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


# 4. Random Number Generation

In [6]:
# Random integers
rand_ints = np.random.randint(1, 10, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Random floats
rand_floats = np.random.rand(2, 4)
print("Random Floats:\n", rand_floats)

# Normal distribution
rand_norm = np.random.randn(5)
print("Random Normal:", rand_norm)

Random Integers:
 [[2 3 2]
 [6 9 5]
 [3 6 1]]
Random Floats:
 [[0.72272574 0.75436418 0.8951181  0.05912836]
 [0.51429256 0.69665429 0.74936019 0.52113244]]
Random Normal: [-0.85772167  2.27471309 -0.29443914  0.57360451 -0.5519492 ]


# 5. Small Exercise

In [7]:
# Exercise: Create an array of 100 random numbers and calculate mean & std
data = np.random.randint(1, 100, 100)
print("Data:", data[:10], "...")  # preview
print("Mean:", np.mean(data))
print("Std Dev:", np.std(data))

Data: [48 87 38  4 15 63 73 64 23 98] ...
Mean: 48.03
Std Dev: 27.80016366858296


# ✅ Summary (Day 4):

Performed element-wise operations
Calculated statistics (mean, std, var)
Practiced matrix multiplication & transpose
Used NumPy’s random module for data simulation